name: listing, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
     - uses: actions/checkout@v2
     - name: Starting Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - name: install modules
       run: npm install
     - name: production build
       run: npm run build:prod
     - name: fix linting typescript
       run: npm run lint:ts:fix
     - name: fix linting scss
       run: npm run lint:scss:fix
     - name: unit testing
       run: npm run test:jest
     - name: build storybook
       run: npm run storybook:build
     - name: screenshot testing
       run: npm run test:loki:ci
     




